### PR TITLE
Fix media section sdp for rejected datachannels

### LINKED ISSUE #166: error thrown in createOffer for a rejected datachannel
```
    describe('rejects a legacy datachannel offer', () => {
...
      it.only('in setRemoteDescription with a local track', () => {
        // test that we don't forget about the track.
        return navigator.mediaDevices.getUserMedia({audio: true})
          .then((stream) => {
            pc.addTrack(stream.getTracks()[0], stream);
            return pc.setRemoteDescription({type: 'offer', sdp: sdp});
          })
          .then(() => pc.createAnswer())
          .then((answer) => pc.setLocalDescription(answer))
          .then(() => pc.createOffer())
          .then((offer) => {
            const sections = SDPUtils.getMediaSections(offer.sdp);
            expect(sections).to.have.length(2);
            expect(SDPUtils.isRejected(sections[0])).to.equal(true);
            expect(SDPUtils.kind(sections[1])).to.equal('audio');
          });
      });
```
This does weird stuff in createOffer, creating an ice gatherer for the rejected m-line and then failing.

### PR DESCRIPTION
**Pull request by syerrapragada**
@fippo Attempt to fix #166

### CODE REVIEW

File: rtcpeerconnection.js [hunk 1]
```diff
@@ -1235,18 +1242,24 @@ module.exports = function(window, edgeVersion) {
     var sdp = SDPUtils.writeSessionBoilerplate(pc._sdpSessionId,
       pc._sdpSessionVersion++);
     pc._transceivers.forEach(function(transceiver, sdpMLineIndex) {
+      if (transceiver.rejected) {
```
Comment (syerrapragada) [inline rtcpeerconnection.js]: This could cause problems with Ice gathering in case if Rejected m= is in index 0. Move this after creatingIceGatherer for the transceiver below?

File: rtcpeerconnection.js [hunk 2]
```diff
@@ -13,7 +13,9 @@ var shimIceGatherer = require('./rtcicegatherer');
 var shimIceTransport = require('./rtcicetransport');
 var shimDtlsTransport = require('./rtcdtlstransport');
 var getCommonCapabilities = require('./getcommoncapabilities');
-var writeMediaSection = require('./writemediasection');
+var writeMediaSection = require('./writemediasection').writeMediaSection;
```
Comment (fippo) [inline rtcpeerconnection.js:16]: this is a bit ugly but will get better with ES6.

File: rtcpeerconnection.js [hunk 3]
```diff
@@ -183,9 +185,11 @@ module.exports = function(window, edgeVersion) {
   };
 
   // start gathering from an RTCIceGatherer.
-  RTCPeerConnection.prototype._gather = function(mid, sdpMLineIndex) {
+  RTCPeerConnection.prototype._gather = function(transceiver) {
     var pc = this;
-    var iceGatherer = this._transceivers[sdpMLineIndex].iceGatherer;
+    var mid = transceiver.mid;
```
Comment (fippo) [inline rtcpeerconnection.js:190]: this is going to work great great with ES6 object destructuring :-)

File: rtcpeerconnection.js [hunk 4]
```diff
@@ -168,9 +170,9 @@ module.exports = function(window, edgeVersion) {
     return transceiver;
   };
 
-  RTCPeerConnection.prototype._createIceGatherer = function(sdpMLineIndex,
+  RTCPeerConnection.prototype._createIceGatherer = function(transceiver,
```
Comment (fippo) [inline rtcpeerconnection.js:173]: passing transceiver here is done for the sake of a consistent internal API?

File: rtcpeerconnection.js [hunk 5]
```diff
@@ -403,7 +406,9 @@ module.exports = function(window, edgeVersion) {
       failed: 0
     };
     this._transceivers.forEach(function(transceiver) {
-      states[transceiver.iceTransport.state]++;
+      if (!transceiver.rejected) {
```
Comment (fippo) [inline rtcpeerconnection.js]: i ended up doing the same in #175. Mine is a bit more defensive but yours is easier in terms of branch coverage in unit tests

File: rtcpeerconnection.js [hunk 6]
```diff
@@ -294,15 +297,15 @@ module.exports = function(window, edgeVersion) {
   // Destroy ICE gatherer, ICE transport and DTLS transport.
   // Without triggering the callbacks.
   RTCPeerConnection.prototype._disposeIceAndDtlsTransports = function(
-    sdpMLineIndex) {
-    var iceGatherer = this._transceivers[sdpMLineIndex].iceGatherer;
+    transceiver) {
```
Comment (fippo) [inline rtcpeerconnection.js:300]: unrelated to the PR: I think there needs to be a bunch of removeAllListeners() here.

File: rtcpeerconnection.js [hunk 7]
```diff
@@ -659,9 +666,7 @@ module.exports = function(window, edgeVersion) {
         transceiver.localCapabilities = caps;
       });
 
-      pc._transceivers.forEach(function(transceiver, sdpMLineIndex) {
-        pc._gather(transceiver.mid, sdpMLineIndex);
-      });
+      pc._transceivers.forEach(pc._gather, pc);
```
Comment (fippo) [inline rtcpeerconnection.js]: I think that answers my question from above :-)

File: writemediasection.js [hunk 8]
```diff
@@ -63,4 +63,30 @@ module.exports = function(transceiver, caps, type, stream, dtlsRole) {
...
+    sdp += 'm=video 0 UDP/TLS/RTP/SAVPF 120\r\n' +
+      'a=rtpmap:120 VP8/90000\r\n';
+  }
+  sdp += 'c=IN IP4 0.0.0.0\r\n' +
+    'a=inactive\r\n' +
+    'a=mid:' + transceiver.mid + '\r\n';
+  return sdp;
+}
+
+exports.writeMediaSection = writeMediaSection;
```
Comment (fippo) [inline writemediasection.js]: can you use module.exports = { ... } for style consistency?

**Review by fippo — COMMENTED** [review]
sorry for the late response! Of course bugs happened in the meantime...

Mostly style-nits, feel free to say "no" to any of them.

**Comment by syerrapragada** [comment]
@fippo Thanks for the review. I will address them soon.

File: rtcpeerconnection.js (hunk 2 above)
Comment (syerrapragada) [reply rtcpeerconnection.js:16]: Should I be using ES6 style here?

File: rtcpeerconnection.js (hunk 3 above)
Comment (syerrapragada) [reply rtcpeerconnection.js:190]: Should I start using ES6 style for this PR?

File: rtcpeerconnection.js (hunk 5 above)
Comment (syerrapragada) [reply rtcpeerconnection.js]: I will rebase my PR

**Review by syerrapragada — COMMENTED** [review]
@fippo I pushed more commits addressing your review comments. Could you please kindly review the PR? 
If it looks good I can squash merge?

File: rtcpeerconnection.js (hunk 2 above)
Comment (fippo) [reply rtcpeerconnection.js:16]: not yet. And I doubt it makes sense to port this due to the limited remaining useful lifetime :-/

**Comment by fippo** [comment]
LGTM, sorry for the long delay. Do you want to squash or shall I?

Planning to publish a 2.0.0 with this under the "next" tag. Not sure whether its even worth the effort of QA-ing a major release before Edge switches to Chrome...

**Comment by syerrapragada** [comment]
I dont have permissions to merge. @fippo Could you please squash merge?

**Comment by fippo** [comment]
2.0.0 published on the "next" tag
